---
driver:
  name: vagrant
  customize:
    cableconnected1: "on" # works around a networking problem introduced in Virtualbox 5.1

transport:
  ssh_key: .kitchen/docker_id_rsa
  forward_agent: true


provisioner:
  name: chef_solo
  product_name: chef
  product_version: 13
  environments_path: test/fixtures/environments
  client_rb:
    environment: media_server-test

verifier:
  name: inspec

driver:
  name: vagrant
  provider: virtualbox
  network:
    - ["forwarded_port", {guest: 8989, host: 8989}] # sonarr
    - ["forwarded_port", {guest: 9117, host: 9117}] # jackett
    - ["forwarded_port", {guest: 9091, host: 9091}] # transmission
    - ["forwarded_port", {guest: 32400, host: 32400}] # plex
    - ["forwarded_port", {guest: 80, host: 8080}] # nginx

platforms:
  - name: ubuntu-18.04


suites:
  - name: default
    run_list:
      - recipe[media_server::default]
      - recipe[media_server-test::setup]
    attributes:
