name "media_server"
maintainer "Justin Fitzsimmons"
maintainer_email "justin@fitzsimmons.ca"
license "ISC"
description "media_server"
version "0.1.0"
issues_url "https://github.com/fitzsimmons/media_server/issues"
source_url "https://github.com/fitzsimmons/media_server"

depends "ubuntu"
depends "apt-periodic"
depends "plex"
depends "sonarr"
depends "poise-archive"
depends "poise-service"
depends "terraform"
